### Checked Exception, Unchecked Exception

**Checked Exception**

```java
public class CheckedException extends Exception {
	public CheckedException(String message) {
    	super(message);
    }
}

```

```java
public class ExceptionTest {   
    public ExceptionTest(String position) throws CheckedException {
        if (ExceptionTest.length() != 2) {
            throw new CheckedException(position + "은 위치 값 형식에 맞지 않습니다.");
        }
        
        x = (int) (ExceptionTest.charAt(0) - 'a');
        y = Integer.parseInt(ExceptionTest.substring(1))-1;
    }
    
    [...]
}
```

- Exception을 바로 상속받음
- 컴파일 시점에 예외를 try-catch 하는지 정적으로 확인.
- 만일 컴파일 시점에 예외에 대해 처리(try-catch) 하지 않는다면 컴파일 에러 발생.
- 트랜잭션 rollback 도 안됨
    - Checked Exception 은 복구가 가능하다는 메커니즘을 가지고 있음.( try-catch 문을 통해 ) 이에 따라 Rollback 을 진행하지 않음
- 예외 발생하는 메소드에서 throws 를 이용해 예외를 호출한 메소드에 전달 가능
- Checked Exception 을 처리하기 위해서는 throws 를 이용해 피호출 메소드에서 호출하는 메소드로 예외를 던진다고 할 수 있음.
    - 하지만 이렇게 무분별하게 throws를 사용하면 가독성을 떨어뜨리고 예외 발생 원인을 알기 어려움.
        - 이 경우 try 문에서 발생하는 Checked Exception 을 catch 문 안에서 Unchecked Exception 으로 바꿔주어 예외가 발생한 메소드에서 예외를 처리할 수 있음
        
        ```java
        public static String unCheckedTest(BufferedReader bufferedReader) {
            try {
            	String requestLine = bufferedReader.readLine();
                if (requestLine == null) {
                    throw new UncheckedException("request line이 없습니다.");
            	}
        
              return requestLine;
            } catch (IOException e) {
                throw new UncheckedException("입력 값이 잘못되어 RequestLine 객체를 생성할 수 없습니다.");
            }
        }
        ```
        

**Unchecked Exception**

```java
public class UncheckedException extends RuntimeException {
    public UncheckedException(String message) {
        super(message);
    }
}
```

```java
// throws로 던져지는 IOException은 bufferedReader.readline()에서 던지는 예외이다.
public static String UncheckedMethod(BufferedReader bufferedReader) throws IOException {
    String requestLine = bufferedReader.readLine();
    if (requestLine == null) {
        throw new UncheckedException("request line이 없습니다.");
    }

    return requestLine;
}
```

- RuntimeException을 상속받음.
- 컴파일 시점에 예외를 try-catch 하는지 확인하지 않음.
- 컴파일 시점에 예외가 발생하는지 판단할 수 없음
- 트랜잭션 rollback 도 가능
- 예외 발생하는 메소드에서 throws 를 이용해 예외 처리할 필요 없음. 처리 해도 됨.(처리를 강제하지 않음)
- 호출하는 메소드가 예외처리를 할 수 없다면 Unchecked Exception 활용 가능. 호출된 메소드에서 예외를 터트려 에러를 처리할 수 있도록함

### 따라서,

- 일반적으로 Checked Exception 예외가 발생했을 경우 복구할 수 있는 경우가 많지 않음
    - ex) 유니크 해야하는 이메일이 중복되어 SQLException 이 발생한다면, 이메일 + 난수 를 입력해 insert 하면 가능하겠지만 현실에서는 RuntimeException 을 발생시키고 입력을 다시 유도함.
- 여기서 중요한 것은 Exception 을 발생시킬 때 명확하게 어떤 예외가 발생해서 Exception 이 발생했는지 정보를 전달하는 것. Checked Exception 을 만나면 더 구체적인 Unchecked Exception 을 발생시켜 정확한 정보를 전달하고 로직의 흐름을 끊어야함.
- 예외 복구 전략이 명확하고 그것이 가능하다면 Checked Exception 을 try-catch 로 잡고 복구 가능. 하지만 그러한 경우는 흔하지 않으며 Checked Exception이 발생하면 더 구체적인 Unchecked Exception을 발생시키고 예외에 대한 메시지를 명확하게 전달하는 것이 좋음.
- 무책임하게 상위 메소드로 throw를 던지는 것은 지양하는 것이 좋음. 상위 메소드의 책임이 그만큼 증가하기 때문